export const SET_AS_LOGGED_IN = 'SET_AS_LOGGED_IN'
export const SET_AS_LOGGED_OUT = 'SET_AS_LOGGED_OUT'
export const SET_IF_SHOULD_BE_LOGGED_IN = 'SET_IF_SHOULD_BE_LOGGED_IN'
export const SET_USER_DATA = 'SET_USER_DATA'